
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma generate && npm run dev"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb

volumes:
  postgres-data:
